### ISSUE TITLE
References to macros not properly recognized in docstrings

### ISSUE THREAD

**Issue by goose121** [mmontone/cl-docweaver#1]
When the documentation string parser comes across a symbol name in a docstring, it assigns it a type `:fn` if it is fbound. This later makes a reference of type `function` to the symbol in the documentation, even if the symbol is actually bound to a macro or a special operator (both of which are considered to be fbound). A fix for this would be to use `special-operator-p` and `macro-function` to differentiate macros and special operators from functions, and possibly to ignore special operators as they do not generally require documentation links.

**Comment by mmontone** [comment]
Ah. Good catch. I'll have a look.

**Comment by mmontone** [comment]
I've made it parse macros and special operators now:

```lisp
CL-USER> (def-properties:parse-docstring "IF WITH-OUTPUT-TO-STRING FUNCTION PRINT" nil)
("" (:SPECIAL-OPERATOR "IF" IF) " "
 (:MACRO "WITH-OUTPUT-TO-STRING" WITH-OUTPUT-TO-STRING) " "
 (:SPECIAL-OPERATOR "FUNCTION" FUNCTION) " " (:FN "PRINT" PRINT))
```
Note that cl-docweaver depends on this library now: https://github.com/mmontone/cl-def-properties
